language: objective-c
osx_image: xcode7.3
xcode_workspace: ADPuzzleAnimation.xcworkspace
xcode_scheme: ADPuzzleAnimation
xcode_sdk: iphonesimulator9.3
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - gem install bundler --no-rdoc --no-ri --no-document --quiet
  - bundle install
script:
  - xctool -workspace ADPuzzleAnimation.xcworkspace -scheme ADPuzzleAnimation build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
